/* Placeholder property data for Stayease */
export const properties = [
  {
    id: 1,
    title: "Modern Beach Villa",
    location: "Malibu, California",
    price: 350,
    image: "/modern-beach-villa-california.jpg",
    description: "Stunning oceanfront villa with private beach access",
    rating: 4.8,
    reviews: 128,
    guests: 6,
    bedrooms: 4,
    bathrooms: 3,
    amenities: ["WiFi", "Pool", "Hot Tub", "Ocean View", "Parking"],
    gallery: [
      "/luxury-beach-villa-living-room.jpg",
      "/modern-bedroom-ocean-view.jpg",
      "/infinity-pool-california-villa.jpg",
      "/kitchen-modern-luxury-villa.jpg",
    ],
  },
  {
    id: 2,
    title: "Cozy Mountain Cabin",
    location: "Aspen, Colorado",
    price: 280,
    image: "/cozy-mountain-cabin-aspen.png",
    description: "Charming cabin nestled in the Rocky Mountains",
    rating: 4.9,
    reviews: 92,
    guests: 4,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["Fireplace", "WiFi", "Mountain View", "Parking", "Heating"],
    gallery: [
      "/cozy-cabin-interior-fireplace.jpg",
      "/mountain-cabin-bedroom.png",
      "/mountain-view-from-cabin.jpg",
      "/cabin-kitchen-rustic.jpg",
    ],
  },
  {
    id: 3,
    title: "Urban Loft Apartment",
    location: "New York, New York",
    price: 320,
    image: "/urban-loft-apartment-ny.jpg",
    description: "Stylish loft in the heart of Manhattan with city views",
    rating: 4.7,
    reviews: 156,
    guests: 5,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["WiFi", "Gym", "City View", "Parking", "Doorman"],
    gallery: [
      "/modern-urban-loft.png",
      "/loft-apartment-bedroom-nyc.jpg",
      "/city-view-from-loft-window.jpg",
      "/loft-kitchen-contemporary.jpg",
    ],
  },
  {
    id: 4,
    title: "Tropical Island Bungalow",
    location: "Bali, Indonesia",
    price: 150,
    image: "/tropical-bungalow-bali.jpg",
    description: "Authentic tropical bungalow with jungle surroundings",
    rating: 4.9,
    reviews: 203,
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Outdoor Shower", "Garden", "Beach Access", "AC"],
    gallery: [
      "/tropical-bungalow-bali-interior.jpg",
      "/bungalow-bedroom-tropical.jpg",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: 5,
    title: "European Manor House",
    location: "Tuscany, Italy",
    price: 420,
    image: "/placeholder.svg?height=300&width=400",
    description: "Historic manor house surrounded by vineyards",
    rating: 4.8,
    reviews: 87,
    guests: 8,
    bedrooms: 5,
    bathrooms: 4,
    amenities: ["Wine Cellar", "Pool", "Vineyard View", "WiFi", "Chef Kitchen"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: 6,
    title: "Tokyo Contemporary Apartment",
    location: "Tokyo, Japan",
    price: 200,
    image: "/placeholder.svg?height=300&width=400",
    description: "Modern apartment in vibrant Shibuya district",
    rating: 4.6,
    reviews: 134,
    guests: 3,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["WiFi", "Rooftop Access", "Modern Kitchen", "Laundry", "AC"],
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
]
